<?php

namespace Database\Seeders;

use App\Models\Company;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CompanySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //

        Company::firstOrCreate(['companyName'=>'Aculife Healthcare Private Ltd']);
        Company::firstOrCreate(['companyName'=>'Agog Pharma Ltd']);
        Company::firstOrCreate(['companyName'=>'Angiplast Private Ltd']);
        Company::firstOrCreate(['companyName'=>'Aristo Pharmaceuticals Private Ltd']);
        Company::firstOrCreate(['companyName'=>'Astra Lifecare (India) Private Ltd']);
        Company::firstOrCreate(['companyName'=>'Aurobindo Pharma Ltd']);
        Company::firstOrCreate(['companyName'=>'Bal Pharma Ltd']);
        Company::firstOrCreate(['companyName'=>'Bharat Serum and Vaccines Ltd']);
        Company::firstOrCreate(['companyName'=>'Biocon Ltd']);
        Company::firstOrCreate(['companyName'=>'Bliss GVS Pharma Ltd']);
        Company::firstOrCreate(['companyName'=>'Cadila Healthcare Pvt Ltd']);
        Company::firstOrCreate(['companyName'=>'Cadila Pharmaceuticals Ltd']);
        Company::firstOrCreate(['companyName'=>'Cipla Limited']);
        Company::firstOrCreate(['companyName'=>'Cupid Limited']);
        Company::firstOrCreate(['companyName'=>'Deluxe Scientific Surgical Pvt Ltd']);
        Company::firstOrCreate(['companyName'=>'Entod Pharmaceuticals Ltd']);
        Company::firstOrCreate(['companyName'=>'Galentic Pharma (India) Pvt Ltd']);
        Company::firstOrCreate(['companyName'=>'Glenmark Ltd']);
        Company::firstOrCreate(['companyName'=>'Globela Pharma Pvt Ltd']);
        Company::firstOrCreate(['companyName'=>'Healthium Medtech Pvt ltd']);
        Company::firstOrCreate(['companyName'=>'Hexagon Nutrition (International) Pvt Ltd']);
        Company::firstOrCreate(['companyName'=>'Hospital Equipment Manufacturing Co. Ltd']);
        Company::firstOrCreate(['companyName'=>'ILife Medical Devices PVT Ltd']);
        Company::firstOrCreate(['companyName'=>'Indi Pharma Pvt Ltd']);
        Company::firstOrCreate(['companyName'=>'Indichemie Health Specialties Pvt Ltd']);
        Company::firstOrCreate(['companyName'=>'Indoco Remedies Limited']);
        Company::firstOrCreate(['companyName'=>'Ind-swift Ltd']);
        Company::firstOrCreate(['companyName'=>'Innovata Pharmaceuticals']);
        Company::firstOrCreate(['companyName'=>'INTAS Pharmaceutical Ltd']);
        Company::firstOrCreate(['companyName'=>'IPCA laboratories Limited']);
        Company::firstOrCreate(['companyName'=>'Jai Pharma']);
        Company::firstOrCreate(['companyName'=>'Kopran Ltd']);
        Company::firstOrCreate(['companyName'=>'Lifeon Labs Pvt Ltd']);
        Company::firstOrCreate(['companyName'=>'Macleods Pharma Limited']);
        Company::firstOrCreate(['companyName'=>'Mankind Pharma Ltd']);
        Company::firstOrCreate(['companyName'=>'Medical Hospital Supplies India']);
        Company::firstOrCreate(['companyName'=>'Medispace Solution']);
        Company::firstOrCreate(['companyName'=>'Medopharm']);
        Company::firstOrCreate(['companyName'=>'Meyer Organics']);
        Company::firstOrCreate(['companyName'=>'Micromaster Laboratories Pvt Ltd']);
        Company::firstOrCreate(['companyName'=>'Milan Laboratories (India) Pvt Ltd']);
        Company::firstOrCreate(['companyName'=>'MRK Healthcare Pvt Ltd']);
        Company::firstOrCreate(['companyName'=>'MSN Laboratories Pvt Ltd']);
        Company::firstOrCreate(['companyName'=>'Mylan Laboratories Ltd']);
        Company::firstOrCreate(['companyName'=>'Naari Pharma Pvt Ltd']);
        Company::firstOrCreate(['companyName'=>'Nector Lifesciences Ltd']);
        Company::firstOrCreate(['companyName'=>'Neon Laboratories Ltd']);
        Company::firstOrCreate(['companyName'=>'Otsuka Pharmaceutical India Pvt Ltd']);
        Company::firstOrCreate(['companyName'=>'Pharma International Co. Ltd']);
        Company::firstOrCreate(['companyName'=>'Poly Medicure Ltd']);
        Company::firstOrCreate(['companyName'=>'R.N. Laboratories Pvt Ltd']);
        Company::firstOrCreate(['companyName'=>'S Kant Healthcare Ltd']);
        Company::firstOrCreate(['companyName'=>'Sance Laboratories Private Ltd']);
        Company::firstOrCreate(['companyName'=>'Serum Institute of India Pvt Ltd']);
        Company::firstOrCreate(['companyName'=>'Shine Pharmaceuticals Ltd']);
        Company::firstOrCreate(['companyName'=>'Sparsh Bio - Tech Pvt. Ltd']);
        Company::firstOrCreate(['companyName'=>'St. Mary Rubber Pvt Ltd']);
        Company::firstOrCreate(['companyName'=>'Sun Pharmaceuticals Industries Ltd']);
        Company::firstOrCreate(['companyName'=>'Swiss Parenterals Ltd']);
        Company::firstOrCreate(['companyName'=>'Trugen Pharmaceuticals Pvt Ltd']);
        Company::firstOrCreate(['companyName'=>'Umedica Laboratories PVT Ltd']);
        Company::firstOrCreate(['companyName'=>'Unilab chemicals & pharmaceuticals Pvt Ltd']);
        Company::firstOrCreate(['companyName'=>'Unique Laboratories Ltd']);
        Company::firstOrCreate(['companyName'=>'United Poly Engineering Pvt Limited']);
        Company::firstOrCreate(['companyName'=>'United Surgical Industries']);
        Company::firstOrCreate(['companyName'=>'Unosource Pharma Ltd']);
        Company::firstOrCreate(['companyName'=>'Verve Human Care Laboratories']);
        Company::firstOrCreate(['companyName'=>'VHB Medisciences Limited']);
        Company::firstOrCreate(['companyName'=>'Vital Health Care']);
        Company::firstOrCreate(['companyName'=>'Wockhardt Ltd']);
        Company::firstOrCreate(['companyName'=>'Zota Healthcare Ltd']);
        Company::firstOrCreate(['companyName'=>'Revital Healthcare (EPZ) Ltd']);
        Company::firstOrCreate(['companyName'=>'Laboratory & Allied Ltd']);
        Company::firstOrCreate(['companyName'=>'Elys Chemicals Industries Ltd']);
        Company::firstOrCreate(['companyName'=>'Cosmos Ltd']);
        Company::firstOrCreate(['companyName'=>'Regal Pharmaceuticals Ltd']);
        Company::firstOrCreate(['companyName'=>'Ivee Infusions EPZ Ltd']);
        Company::firstOrCreate(['companyName'=>'Medionics HealthCare Ltd']);
        Company::firstOrCreate(['companyName'=>'Pfizer Laboratories Ltd']);
        Company::firstOrCreate(['companyName'=>'Universal Corporation Ltd']);
        Company::firstOrCreate(['companyName'=>'Medical Stores Department']);
        Company::firstOrCreate(['companyName'=>'Ministry of Health']);
        Company::firstOrCreate(['companyName'=>'Ministry of Foreign Affairs']);
        Company::firstOrCreate(['companyName'=>'Tanzania Pharmaceuticals Manufacturers Association']);
        Company::firstOrCreate(['companyName'=>'Abacus Parenteral Drugs Ltd']);
        Company::firstOrCreate(['companyName'=>'21st Century Textile Ltd']);
        Company::firstOrCreate(['companyName'=>'A to Z Textile Mills Ltd']);
        Company::firstOrCreate(['companyName'=>'A.A. Pharmaceuticals Ltd']);
        Company::firstOrCreate(['companyName'=>'Bingwa Laboratories Ltd']);
        Company::firstOrCreate(['companyName'=>'Jaffery Ind.Saini Ltd']);
        Company::firstOrCreate(['companyName'=>'Keko Pharmaceuticals Industries (1997) Ltd']);
        Company::firstOrCreate(['companyName'=>'Kishan Industries']);
        Company::firstOrCreate(['companyName'=>'Mansoor Daya Chemicals Ltd']);
        Company::firstOrCreate(['companyName'=>'Modern Mattress Manufacturing Ltd']);
        Company::firstOrCreate(['companyName'=>'Msagara Investment Co. Ltd']);
        Company::firstOrCreate(['companyName'=>'MSD Mask Production Unit']);
        Company::firstOrCreate(['companyName'=>'Nellys Trade Link Co. Ltd']);
        Company::firstOrCreate(['companyName'=>'Nida Textile Mills (T) Ltd']);
        Company::firstOrCreate(['companyName'=>'Prince Pharmaceuticals Co. Ltd']);
        Company::firstOrCreate(['companyName'=>'SG Star Pharmaceuticals Ltd']);
        Company::firstOrCreate(['companyName'=>'Shelys Pharmaceuticals']);
        Company::firstOrCreate(['companyName'=>'Soap and Allied Industries']);
        Company::firstOrCreate(['companyName'=>'Sri Balaji Pharma Ltd']);
        Company::firstOrCreate(['companyName'=>'Sunflag Tanzania Limited']);
        Company::firstOrCreate(['companyName'=>'Tanzania Biotech Product Ltd']);
        Company::firstOrCreate(['companyName'=>'Tanzania Printing Servicess']);
        Company::firstOrCreate(['companyName'=>'TLL Printing and Packaging Ltd']);
        Company::firstOrCreate(['companyName'=>'Vita Form (T) Ltd']);
        Company::firstOrCreate(['companyName'=>'Zenufa Laboratories Ltd']);
        Company::firstOrCreate(['companyName'=>'Square Pharmaceuticals Ltd']);
        Company::firstOrCreate(['companyName'=>'Abbott Diagnostics Korea Inc']);
        Company::firstOrCreate(['companyName'=>'Boditech Med Inc']);
        Company::firstOrCreate(['companyName'=>'Sitec Medical Co. Ltd']);
        Company::firstOrCreate(['companyName'=>'Standard Diagnostics Inc']);
        Company::firstOrCreate(['companyName'=>'Oxus Co., Ltd']);
        Company::firstOrCreate(['companyName'=>'Varichem Pharmaceuticals Ltd']);
        Company::firstOrCreate(['companyName'=>'BILIM ILAC']);
        Company::firstOrCreate(['companyName'=>'Pharmalab Ltd']);
        Company::firstOrCreate(['companyName'=>'Camp Medica Group']);
        Company::firstOrCreate(['companyName'=>'Belaseptika AG']);
        Company::firstOrCreate(['companyName'=>'YSP Industries (M) sdn. BHD']);
        Company::firstOrCreate(['companyName'=>'Brookes Pharma (Pvt) Ltd']);
        Company::firstOrCreate(['companyName'=>'Norflolk International']);
        Company::firstOrCreate(['companyName'=>'Nabiqasim Industries (Pvt) Limited']);
        Company::firstOrCreate(['companyName'=>'CCL Pharmaceuticals Ltd']);
        Company::firstOrCreate(['companyName'=>'Mega Lifesciences Plc']);
        Company::firstOrCreate(['companyName'=>'Sri Tang Agro Industry Plc']);
        Company::firstOrCreate(['companyName'=>'Abbot Product Operations AG']);
        Company::firstOrCreate(['companyName'=>'Novartis Pharma Services AG']);
        Company::firstOrCreate(['companyName'=>'Octa Pharma']);
        Company::firstOrCreate(['companyName'=>'F. Hoffmann-La Roche']);
        Company::firstOrCreate(['companyName'=>'Medivision (Pty) Ltd']);
        Company::firstOrCreate(['companyName'=>'Abbvie (Pty) Ltd']);
        Company::firstOrCreate(['companyName'=>'Roche Diabetes Care']);
        Company::firstOrCreate(['companyName'=>'EIPICO']);
        Company::firstOrCreate(['companyName'=>'South Egypt Drug Industries Co. Ltd']);
        Company::firstOrCreate(['companyName'=>'PHARCO Pharmaceuticals']);
        Company::firstOrCreate(['companyName'=>'Kollsut International Inc']);
        Company::firstOrCreate(['companyName'=>'Gradian Health Systems']);
        Company::firstOrCreate(['companyName'=>'21st Century Healthcare Inc']);
        Company::firstOrCreate(['companyName'=>'Julphar']);
        Company::firstOrCreate(['companyName'=>'PT. MEGA ANDALAN KALSAN']);
        Company::firstOrCreate(['companyName'=>'PT. HARSEN']);
        Company::firstOrCreate(['companyName'=>'DiaSorin S.p.A']);
        Company::firstOrCreate(['companyName'=>'Fazzini SRL']);
        Company::firstOrCreate(['companyName'=>'Becton Dicknson Int. (BDI)']);
        Company::firstOrCreate(['companyName'=>'TMDA']);
        Company::firstOrCreate(['companyName'=>'TRA']);
        Company::firstOrCreate(['companyName'=>'CRDB']);
        Company::firstOrCreate(['companyName'=>'NMB']);
        Company::firstOrCreate(['companyName'=>'NBC']);
        Company::firstOrCreate(['companyName'=>'TPB']);
        // Company::firstOrCreate(['companyName'=>'']);
        // Company::firstOrCreate(['companyName'=>'']);
        // Company::firstOrCreate(['companyName'=>'']);
    }
}
